<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>key_917e66ef78164716386f5da926d39bdc7</code>
 */
class key_917e66ef78164716386f5da926d39bdc7 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 key15f93f983524def3dca464469d2cf9f3e = 1;</code>
     */
    protected $key15f93f983524def3dca464469d2cf9f3e = 0;
    /**
     * Generated from protobuf field <code>fixed32 key2a322852ce0df73e204b7e67cbbef0d0a = 2;</code>
     */
    protected $key2a322852ce0df73e204b7e67cbbef0d0a = 0;
    /**
     * Generated from protobuf field <code>fixed32 key3a87ff679a2f3e71d9181a67b7542122c = 3;</code>
     */
    protected $key3a87ff679a2f3e71d9181a67b7542122c = 0;
    /**
     * Generated from protobuf field <code>.key_3f0353039e1b2b387140a07447a756407 unknown1 = 4;</code>
     */
    protected $unknown1 = null;
    /**
     * Generated from protobuf field <code>string key624528d091c529bdb075463b6c9dde754 = 6;</code>
     */
    protected $key624528d091c529bdb075463b6c9dde754 = '';
    /**
     * Generated from protobuf field <code>double key917e66ef78164716386f5da926d39bdc7 = 9;</code>
     */
    protected $key917e66ef78164716386f5da926d39bdc7 = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $key15f93f983524def3dca464469d2cf9f3e
     *     @type int $key2a322852ce0df73e204b7e67cbbef0d0a
     *     @type int $key3a87ff679a2f3e71d9181a67b7542122c
     *     @type \key_3f0353039e1b2b387140a07447a756407 $unknown1
     *     @type string $key624528d091c529bdb075463b6c9dde754
     *     @type float $key917e66ef78164716386f5da926d39bdc7
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>fixed32 key15f93f983524def3dca464469d2cf9f3e = 1;</code>
     * @return int
     */
    public function getKey15F93F983524Def3Dca464469D2Cf9F3E()
    {
        return $this->key15f93f983524def3dca464469d2cf9f3e;
    }

    /**
     * Generated from protobuf field <code>fixed32 key15f93f983524def3dca464469d2cf9f3e = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setKey15F93F983524Def3Dca464469D2Cf9F3E($var)
    {
        GPBUtil::checkUint32($var);
        $this->key15f93f983524def3dca464469d2cf9f3e = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key2a322852ce0df73e204b7e67cbbef0d0a = 2;</code>
     * @return int
     */
    public function getKey2A322852Ce0Df73E204B7E67Cbbef0D0A()
    {
        return $this->key2a322852ce0df73e204b7e67cbbef0d0a;
    }

    /**
     * Generated from protobuf field <code>fixed32 key2a322852ce0df73e204b7e67cbbef0d0a = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setKey2A322852Ce0Df73E204B7E67Cbbef0D0A($var)
    {
        GPBUtil::checkUint32($var);
        $this->key2a322852ce0df73e204b7e67cbbef0d0a = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key3a87ff679a2f3e71d9181a67b7542122c = 3;</code>
     * @return int
     */
    public function getKey3A87Ff679A2F3E71D9181A67B7542122C()
    {
        return $this->key3a87ff679a2f3e71d9181a67b7542122c;
    }

    /**
     * Generated from protobuf field <code>fixed32 key3a87ff679a2f3e71d9181a67b7542122c = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setKey3A87Ff679A2F3E71D9181A67B7542122C($var)
    {
        GPBUtil::checkUint32($var);
        $this->key3a87ff679a2f3e71d9181a67b7542122c = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.key_3f0353039e1b2b387140a07447a756407 unknown1 = 4;</code>
     * @return \key_3f0353039e1b2b387140a07447a756407
     */
    public function getUnknown1()
    {
        return $this->unknown1;
    }

    /**
     * Generated from protobuf field <code>.key_3f0353039e1b2b387140a07447a756407 unknown1 = 4;</code>
     * @param \key_3f0353039e1b2b387140a07447a756407 $var
     * @return $this
     */
    public function setUnknown1($var)
    {
        GPBUtil::checkMessage($var, \key_3f0353039e1b2b387140a07447a756407::class);
        $this->unknown1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key624528d091c529bdb075463b6c9dde754 = 6;</code>
     * @return string
     */
    public function getKey624528D091C529Bdb075463B6C9Dde754()
    {
        return $this->key624528d091c529bdb075463b6c9dde754;
    }

    /**
     * Generated from protobuf field <code>string key624528d091c529bdb075463b6c9dde754 = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setKey624528D091C529Bdb075463B6C9Dde754($var)
    {
        GPBUtil::checkString($var, True);
        $this->key624528d091c529bdb075463b6c9dde754 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double key917e66ef78164716386f5da926d39bdc7 = 9;</code>
     * @return float
     */
    public function getKey917E66Ef78164716386F5Da926D39Bdc7()
    {
        return $this->key917e66ef78164716386f5da926d39bdc7;
    }

    /**
     * Generated from protobuf field <code>double key917e66ef78164716386f5da926d39bdc7 = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setKey917E66Ef78164716386F5Da926D39Bdc7($var)
    {
        GPBUtil::checkDouble($var);
        $this->key917e66ef78164716386f5da926d39bdc7 = $var;

        return $this;
    }

}

