<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>key_863e33e1b7c536b8b6e462b15467a9fbf1</code>
 */
class key_863e33e1b7c536b8b6e462b15467a9fbf1 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key1218e46a3dda39e239c59a80b5d0526508 = 12;</code>
     */
    protected $key1218e46a3dda39e239c59a80b5d0526508 = '';
    /**
     * Generated from protobuf field <code>string key13189cc793e8d6be8b4bfce4ca55d8ae1d = 13;</code>
     */
    protected $key13189cc793e8d6be8b4bfce4ca55d8ae1d = '';
    /**
     * Generated from protobuf field <code>int32 key16eccbc87e4b5ce2fe28308fd9f2a7baf3 = 16;</code>
     */
    protected $key16eccbc87e4b5ce2fe28308fd9f2a7baf3 = 0;
    /**
     * Generated from protobuf field <code>string key17d627cabbdf951974157c48b24fa9b779 = 17;</code>
     */
    protected $key17d627cabbdf951974157c48b24fa9b779 = '';
    /**
     * Generated from protobuf field <code>string key1811534e01ccf9b2ac5f68d7f99b214c04 = 18;</code>
     */
    protected $key1811534e01ccf9b2ac5f68d7f99b214c04 = '';
    /**
     * Generated from protobuf field <code>.key_629159437e0692991a4d3698abb8d3b1d unknownoo = 19;</code>
     */
    protected $unknownoo = null;
    /**
     * Generated from protobuf field <code>.key_1231d84139b3324b9a369643c152f8883f unknown1 = 21;</code>
     */
    protected $unknown1 = null;
    /**
     * Generated from protobuf field <code>string key227a20c4af648fdfb4a3e5fce3d812aab5 = 22;</code>
     */
    protected $key227a20c4af648fdfb4a3e5fce3d812aab5 = '';
    /**
     * Generated from protobuf field <code>string key25c22399173c08d90a77ec84c7179b8d62 = 25;</code>
     */
    protected $key25c22399173c08d90a77ec84c7179b8d62 = '';
    /**
     * Generated from protobuf field <code>int32 key37e7b24b112a44fdd9ee93bdf998c6ca0e = 37;</code>
     */
    protected $key37e7b24b112a44fdd9ee93bdf998c6ca0e = 0;
    /**
     * Generated from protobuf field <code>int32 key384ffce04d92a4d6cb21c1494cdfcd6dc1 = 38;</code>
     */
    protected $key384ffce04d92a4d6cb21c1494cdfcd6dc1 = 0;
    /**
     * Generated from protobuf field <code>fixed32 key3971c2ed8acaaf28200d99658c3d76ff7d = 39;</code>
     */
    protected $key3971c2ed8acaaf28200d99658c3d76ff7d = 0;
    /**
     * Generated from protobuf field <code>fixed32 key40f3f06a3c5ba5ed8cb21e90179a95e347 = 40;</code>
     */
    protected $key40f3f06a3c5ba5ed8cb21e90179a95e347 = 0;
    /**
     * Generated from protobuf field <code>int32 key41c81e728d9d4c2f636f067f89cc14862c = 41;</code>
     */
    protected $key41c81e728d9d4c2f636f067f89cc14862c = 0;
    /**
     * Generated from protobuf field <code>int32 key46c4ca4238a0b923820dcc509a6f75849b = 46;</code>
     */
    protected $key46c4ca4238a0b923820dcc509a6f75849b = 0;
    /**
     * Generated from protobuf field <code>int32 key502baa9205391414503d5ccb495a029f9c = 50;</code>
     */
    protected $key502baa9205391414503d5ccb495a029f9c = 0;
    /**
     * Generated from protobuf field <code>int32 key52a87ff679a2f3e71d9181a67b7542122c = 52;</code>
     */
    protected $key52a87ff679a2f3e71d9181a67b7542122c = 0;
    /**
     * Generated from protobuf field <code>int32 key55e7b24b112a44fdd9ee93bdf998c6ca0e = 55;</code>
     */
    protected $key55e7b24b112a44fdd9ee93bdf998c6ca0e = 0;
    /**
     * Generated from protobuf field <code>int32 key564ffce04d92a4d6cb21c1494cdfcd6dc1 = 56;</code>
     */
    protected $key564ffce04d92a4d6cb21c1494cdfcd6dc1 = 0;
    /**
     * Generated from protobuf field <code>int32 key61eccbc87e4b5ce2fe28308fd9f2a7baf3 = 61;</code>
     */
    protected $key61eccbc87e4b5ce2fe28308fd9f2a7baf3 = 0;
    /**
     * Generated from protobuf field <code>.key_59a694d0d6a818c4af304617f622bf617 unknown3 = 62;</code>
     */
    protected $unknown3 = null;
    /**
     * Generated from protobuf field <code>uint32 key64b6d767d2f8ed5d21a44b0e5886680cb9 = 64;</code>
     */
    protected $key64b6d767d2f8ed5d21a44b0e5886680cb9 = 0;
    /**
     * Generated from protobuf field <code>fixed32 key65952eb029834bbd9b2776ce858a169682 = 65;</code>
     */
    protected $key65952eb029834bbd9b2776ce858a169682 = 0;
    /**
     * Generated from protobuf field <code>uint64 key671356fb6a44a61375848e4b6346305ef2 = 67;</code>
     */
    protected $key671356fb6a44a61375848e4b6346305ef2 = 0;
    /**
     * Generated from protobuf field <code>int32 key78c4ca4238a0b923820dcc509a6f75849b = 78;</code>
     */
    protected $key78c4ca4238a0b923820dcc509a6f75849b = 0;
    /**
     * Generated from protobuf field <code>string key8020231c8e224de4d79e923e29e23eb3a0 = 80;</code>
     */
    protected $key8020231c8e224de4d79e923e29e23eb3a0 = '';
    /**
     * Generated from protobuf field <code>string key859d4568c009d203ab10e33ea9953a0264 = 85;</code>
     */
    protected $key859d4568c009d203ab10e33ea9953a0264 = '';
    /**
     * Generated from protobuf field <code>.key_3cfcd208495d565ef66e7dff9f98764da some_data = 86;</code>
     */
    protected $some_data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key1218e46a3dda39e239c59a80b5d0526508
     *     @type string $key13189cc793e8d6be8b4bfce4ca55d8ae1d
     *     @type int $key16eccbc87e4b5ce2fe28308fd9f2a7baf3
     *     @type string $key17d627cabbdf951974157c48b24fa9b779
     *     @type string $key1811534e01ccf9b2ac5f68d7f99b214c04
     *     @type \key_629159437e0692991a4d3698abb8d3b1d $unknownoo
     *     @type \key_1231d84139b3324b9a369643c152f8883f $unknown1
     *     @type string $key227a20c4af648fdfb4a3e5fce3d812aab5
     *     @type string $key25c22399173c08d90a77ec84c7179b8d62
     *     @type int $key37e7b24b112a44fdd9ee93bdf998c6ca0e
     *     @type int $key384ffce04d92a4d6cb21c1494cdfcd6dc1
     *     @type int $key3971c2ed8acaaf28200d99658c3d76ff7d
     *     @type int $key40f3f06a3c5ba5ed8cb21e90179a95e347
     *     @type int $key41c81e728d9d4c2f636f067f89cc14862c
     *     @type int $key46c4ca4238a0b923820dcc509a6f75849b
     *     @type int $key502baa9205391414503d5ccb495a029f9c
     *     @type int $key52a87ff679a2f3e71d9181a67b7542122c
     *     @type int $key55e7b24b112a44fdd9ee93bdf998c6ca0e
     *     @type int $key564ffce04d92a4d6cb21c1494cdfcd6dc1
     *     @type int $key61eccbc87e4b5ce2fe28308fd9f2a7baf3
     *     @type \key_59a694d0d6a818c4af304617f622bf617 $unknown3
     *     @type int $key64b6d767d2f8ed5d21a44b0e5886680cb9
     *     @type int $key65952eb029834bbd9b2776ce858a169682
     *     @type int|string $key671356fb6a44a61375848e4b6346305ef2
     *     @type int $key78c4ca4238a0b923820dcc509a6f75849b
     *     @type string $key8020231c8e224de4d79e923e29e23eb3a0
     *     @type string $key859d4568c009d203ab10e33ea9953a0264
     *     @type \key_3cfcd208495d565ef66e7dff9f98764da $some_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key1218e46a3dda39e239c59a80b5d0526508 = 12;</code>
     * @return string
     */
    public function getKey1218E46A3Dda39E239C59A80B5D0526508()
    {
        return $this->key1218e46a3dda39e239c59a80b5d0526508;
    }

    /**
     * Generated from protobuf field <code>string key1218e46a3dda39e239c59a80b5d0526508 = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setKey1218E46A3Dda39E239C59A80B5D0526508($var)
    {
        GPBUtil::checkString($var, True);
        $this->key1218e46a3dda39e239c59a80b5d0526508 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key13189cc793e8d6be8b4bfce4ca55d8ae1d = 13;</code>
     * @return string
     */
    public function getKey13189Cc793E8D6Be8B4Bfce4Ca55D8Ae1D()
    {
        return $this->key13189cc793e8d6be8b4bfce4ca55d8ae1d;
    }

    /**
     * Generated from protobuf field <code>string key13189cc793e8d6be8b4bfce4ca55d8ae1d = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setKey13189Cc793E8D6Be8B4Bfce4Ca55D8Ae1D($var)
    {
        GPBUtil::checkString($var, True);
        $this->key13189cc793e8d6be8b4bfce4ca55d8ae1d = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 key16eccbc87e4b5ce2fe28308fd9f2a7baf3 = 16;</code>
     * @return int
     */
    public function getKey16Eccbc87E4B5Ce2Fe28308Fd9F2A7Baf3()
    {
        return $this->key16eccbc87e4b5ce2fe28308fd9f2a7baf3;
    }

    /**
     * Generated from protobuf field <code>int32 key16eccbc87e4b5ce2fe28308fd9f2a7baf3 = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setKey16Eccbc87E4B5Ce2Fe28308Fd9F2A7Baf3($var)
    {
        GPBUtil::checkInt32($var);
        $this->key16eccbc87e4b5ce2fe28308fd9f2a7baf3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key17d627cabbdf951974157c48b24fa9b779 = 17;</code>
     * @return string
     */
    public function getKey17D627Cabbdf951974157C48B24Fa9B779()
    {
        return $this->key17d627cabbdf951974157c48b24fa9b779;
    }

    /**
     * Generated from protobuf field <code>string key17d627cabbdf951974157c48b24fa9b779 = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setKey17D627Cabbdf951974157C48B24Fa9B779($var)
    {
        GPBUtil::checkString($var, True);
        $this->key17d627cabbdf951974157c48b24fa9b779 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key1811534e01ccf9b2ac5f68d7f99b214c04 = 18;</code>
     * @return string
     */
    public function getKey1811534E01Ccf9B2Ac5F68D7F99B214C04()
    {
        return $this->key1811534e01ccf9b2ac5f68d7f99b214c04;
    }

    /**
     * Generated from protobuf field <code>string key1811534e01ccf9b2ac5f68d7f99b214c04 = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setKey1811534E01Ccf9B2Ac5F68D7F99B214C04($var)
    {
        GPBUtil::checkString($var, True);
        $this->key1811534e01ccf9b2ac5f68d7f99b214c04 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.key_629159437e0692991a4d3698abb8d3b1d unknownoo = 19;</code>
     * @return \key_629159437e0692991a4d3698abb8d3b1d
     */
    public function getUnknownoo()
    {
        return $this->unknownoo;
    }

    /**
     * Generated from protobuf field <code>.key_629159437e0692991a4d3698abb8d3b1d unknownoo = 19;</code>
     * @param \key_629159437e0692991a4d3698abb8d3b1d $var
     * @return $this
     */
    public function setUnknownoo($var)
    {
        GPBUtil::checkMessage($var, \key_629159437e0692991a4d3698abb8d3b1d::class);
        $this->unknownoo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.key_1231d84139b3324b9a369643c152f8883f unknown1 = 21;</code>
     * @return \key_1231d84139b3324b9a369643c152f8883f
     */
    public function getUnknown1()
    {
        return $this->unknown1;
    }

    /**
     * Generated from protobuf field <code>.key_1231d84139b3324b9a369643c152f8883f unknown1 = 21;</code>
     * @param \key_1231d84139b3324b9a369643c152f8883f $var
     * @return $this
     */
    public function setUnknown1($var)
    {
        GPBUtil::checkMessage($var, \key_1231d84139b3324b9a369643c152f8883f::class);
        $this->unknown1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key227a20c4af648fdfb4a3e5fce3d812aab5 = 22;</code>
     * @return string
     */
    public function getKey227A20C4Af648Fdfb4A3E5Fce3D812Aab5()
    {
        return $this->key227a20c4af648fdfb4a3e5fce3d812aab5;
    }

    /**
     * Generated from protobuf field <code>string key227a20c4af648fdfb4a3e5fce3d812aab5 = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setKey227A20C4Af648Fdfb4A3E5Fce3D812Aab5($var)
    {
        GPBUtil::checkString($var, True);
        $this->key227a20c4af648fdfb4a3e5fce3d812aab5 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key25c22399173c08d90a77ec84c7179b8d62 = 25;</code>
     * @return string
     */
    public function getKey25C22399173C08D90A77Ec84C7179B8D62()
    {
        return $this->key25c22399173c08d90a77ec84c7179b8d62;
    }

    /**
     * Generated from protobuf field <code>string key25c22399173c08d90a77ec84c7179b8d62 = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setKey25C22399173C08D90A77Ec84C7179B8D62($var)
    {
        GPBUtil::checkString($var, True);
        $this->key25c22399173c08d90a77ec84c7179b8d62 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 key37e7b24b112a44fdd9ee93bdf998c6ca0e = 37;</code>
     * @return int
     */
    public function getKey37E7B24B112A44Fdd9Ee93Bdf998C6Ca0E()
    {
        return $this->key37e7b24b112a44fdd9ee93bdf998c6ca0e;
    }

    /**
     * Generated from protobuf field <code>int32 key37e7b24b112a44fdd9ee93bdf998c6ca0e = 37;</code>
     * @param int $var
     * @return $this
     */
    public function setKey37E7B24B112A44Fdd9Ee93Bdf998C6Ca0E($var)
    {
        GPBUtil::checkInt32($var);
        $this->key37e7b24b112a44fdd9ee93bdf998c6ca0e = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 key384ffce04d92a4d6cb21c1494cdfcd6dc1 = 38;</code>
     * @return int
     */
    public function getKey384Ffce04D92A4D6Cb21C1494Cdfcd6Dc1()
    {
        return $this->key384ffce04d92a4d6cb21c1494cdfcd6dc1;
    }

    /**
     * Generated from protobuf field <code>int32 key384ffce04d92a4d6cb21c1494cdfcd6dc1 = 38;</code>
     * @param int $var
     * @return $this
     */
    public function setKey384Ffce04D92A4D6Cb21C1494Cdfcd6Dc1($var)
    {
        GPBUtil::checkInt32($var);
        $this->key384ffce04d92a4d6cb21c1494cdfcd6dc1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key3971c2ed8acaaf28200d99658c3d76ff7d = 39;</code>
     * @return int
     */
    public function getKey3971C2Ed8Acaaf28200D99658C3D76Ff7D()
    {
        return $this->key3971c2ed8acaaf28200d99658c3d76ff7d;
    }

    /**
     * Generated from protobuf field <code>fixed32 key3971c2ed8acaaf28200d99658c3d76ff7d = 39;</code>
     * @param int $var
     * @return $this
     */
    public function setKey3971C2Ed8Acaaf28200D99658C3D76Ff7D($var)
    {
        GPBUtil::checkUint32($var);
        $this->key3971c2ed8acaaf28200d99658c3d76ff7d = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key40f3f06a3c5ba5ed8cb21e90179a95e347 = 40;</code>
     * @return int
     */
    public function getKey40F3F06A3C5Ba5Ed8Cb21E90179A95E347()
    {
        return $this->key40f3f06a3c5ba5ed8cb21e90179a95e347;
    }

    /**
     * Generated from protobuf field <code>fixed32 key40f3f06a3c5ba5ed8cb21e90179a95e347 = 40;</code>
     * @param int $var
     * @return $this
     */
    public function setKey40F3F06A3C5Ba5Ed8Cb21E90179A95E347($var)
    {
        GPBUtil::checkUint32($var);
        $this->key40f3f06a3c5ba5ed8cb21e90179a95e347 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 key41c81e728d9d4c2f636f067f89cc14862c = 41;</code>
     * @return int
     */
    public function getKey41C81E728D9D4C2F636F067F89Cc14862C()
    {
        return $this->key41c81e728d9d4c2f636f067f89cc14862c;
    }

    /**
     * Generated from protobuf field <code>int32 key41c81e728d9d4c2f636f067f89cc14862c = 41;</code>
     * @param int $var
     * @return $this
     */
    public function setKey41C81E728D9D4C2F636F067F89Cc14862C($var)
    {
        GPBUtil::checkInt32($var);
        $this->key41c81e728d9d4c2f636f067f89cc14862c = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 key46c4ca4238a0b923820dcc509a6f75849b = 46;</code>
     * @return int
     */
    public function getKey46C4Ca4238A0B923820Dcc509A6F75849B()
    {
        return $this->key46c4ca4238a0b923820dcc509a6f75849b;
    }

    /**
     * Generated from protobuf field <code>int32 key46c4ca4238a0b923820dcc509a6f75849b = 46;</code>
     * @param int $var
     * @return $this
     */
    public function setKey46C4Ca4238A0B923820Dcc509A6F75849B($var)
    {
        GPBUtil::checkInt32($var);
        $this->key46c4ca4238a0b923820dcc509a6f75849b = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 key502baa9205391414503d5ccb495a029f9c = 50;</code>
     * @return int
     */
    public function getKey502Baa9205391414503D5Ccb495A029F9C()
    {
        return $this->key502baa9205391414503d5ccb495a029f9c;
    }

    /**
     * Generated from protobuf field <code>int32 key502baa9205391414503d5ccb495a029f9c = 50;</code>
     * @param int $var
     * @return $this
     */
    public function setKey502Baa9205391414503D5Ccb495A029F9C($var)
    {
        GPBUtil::checkInt32($var);
        $this->key502baa9205391414503d5ccb495a029f9c = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 key52a87ff679a2f3e71d9181a67b7542122c = 52;</code>
     * @return int
     */
    public function getKey52A87Ff679A2F3E71D9181A67B7542122C()
    {
        return $this->key52a87ff679a2f3e71d9181a67b7542122c;
    }

    /**
     * Generated from protobuf field <code>int32 key52a87ff679a2f3e71d9181a67b7542122c = 52;</code>
     * @param int $var
     * @return $this
     */
    public function setKey52A87Ff679A2F3E71D9181A67B7542122C($var)
    {
        GPBUtil::checkInt32($var);
        $this->key52a87ff679a2f3e71d9181a67b7542122c = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 key55e7b24b112a44fdd9ee93bdf998c6ca0e = 55;</code>
     * @return int
     */
    public function getKey55E7B24B112A44Fdd9Ee93Bdf998C6Ca0E()
    {
        return $this->key55e7b24b112a44fdd9ee93bdf998c6ca0e;
    }

    /**
     * Generated from protobuf field <code>int32 key55e7b24b112a44fdd9ee93bdf998c6ca0e = 55;</code>
     * @param int $var
     * @return $this
     */
    public function setKey55E7B24B112A44Fdd9Ee93Bdf998C6Ca0E($var)
    {
        GPBUtil::checkInt32($var);
        $this->key55e7b24b112a44fdd9ee93bdf998c6ca0e = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 key564ffce04d92a4d6cb21c1494cdfcd6dc1 = 56;</code>
     * @return int
     */
    public function getKey564Ffce04D92A4D6Cb21C1494Cdfcd6Dc1()
    {
        return $this->key564ffce04d92a4d6cb21c1494cdfcd6dc1;
    }

    /**
     * Generated from protobuf field <code>int32 key564ffce04d92a4d6cb21c1494cdfcd6dc1 = 56;</code>
     * @param int $var
     * @return $this
     */
    public function setKey564Ffce04D92A4D6Cb21C1494Cdfcd6Dc1($var)
    {
        GPBUtil::checkInt32($var);
        $this->key564ffce04d92a4d6cb21c1494cdfcd6dc1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 key61eccbc87e4b5ce2fe28308fd9f2a7baf3 = 61;</code>
     * @return int
     */
    public function getKey61Eccbc87E4B5Ce2Fe28308Fd9F2A7Baf3()
    {
        return $this->key61eccbc87e4b5ce2fe28308fd9f2a7baf3;
    }

    /**
     * Generated from protobuf field <code>int32 key61eccbc87e4b5ce2fe28308fd9f2a7baf3 = 61;</code>
     * @param int $var
     * @return $this
     */
    public function setKey61Eccbc87E4B5Ce2Fe28308Fd9F2A7Baf3($var)
    {
        GPBUtil::checkInt32($var);
        $this->key61eccbc87e4b5ce2fe28308fd9f2a7baf3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.key_59a694d0d6a818c4af304617f622bf617 unknown3 = 62;</code>
     * @return \key_59a694d0d6a818c4af304617f622bf617
     */
    public function getUnknown3()
    {
        return $this->unknown3;
    }

    /**
     * Generated from protobuf field <code>.key_59a694d0d6a818c4af304617f622bf617 unknown3 = 62;</code>
     * @param \key_59a694d0d6a818c4af304617f622bf617 $var
     * @return $this
     */
    public function setUnknown3($var)
    {
        GPBUtil::checkMessage($var, \key_59a694d0d6a818c4af304617f622bf617::class);
        $this->unknown3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 key64b6d767d2f8ed5d21a44b0e5886680cb9 = 64;</code>
     * @return int
     */
    public function getKey64B6D767D2F8Ed5D21A44B0E5886680Cb9()
    {
        return $this->key64b6d767d2f8ed5d21a44b0e5886680cb9;
    }

    /**
     * Generated from protobuf field <code>uint32 key64b6d767d2f8ed5d21a44b0e5886680cb9 = 64;</code>
     * @param int $var
     * @return $this
     */
    public function setKey64B6D767D2F8Ed5D21A44B0E5886680Cb9($var)
    {
        GPBUtil::checkUint32($var);
        $this->key64b6d767d2f8ed5d21a44b0e5886680cb9 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key65952eb029834bbd9b2776ce858a169682 = 65;</code>
     * @return int
     */
    public function getKey65952Eb029834Bbd9B2776Ce858A169682()
    {
        return $this->key65952eb029834bbd9b2776ce858a169682;
    }

    /**
     * Generated from protobuf field <code>fixed32 key65952eb029834bbd9b2776ce858a169682 = 65;</code>
     * @param int $var
     * @return $this
     */
    public function setKey65952Eb029834Bbd9B2776Ce858A169682($var)
    {
        GPBUtil::checkUint32($var);
        $this->key65952eb029834bbd9b2776ce858a169682 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 key671356fb6a44a61375848e4b6346305ef2 = 67;</code>
     * @return int|string
     */
    public function getKey671356Fb6A44A61375848E4B6346305Ef2()
    {
        return $this->key671356fb6a44a61375848e4b6346305ef2;
    }

    /**
     * Generated from protobuf field <code>uint64 key671356fb6a44a61375848e4b6346305ef2 = 67;</code>
     * @param int|string $var
     * @return $this
     */
    public function setKey671356Fb6A44A61375848E4B6346305Ef2($var)
    {
        GPBUtil::checkUint64($var);
        $this->key671356fb6a44a61375848e4b6346305ef2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 key78c4ca4238a0b923820dcc509a6f75849b = 78;</code>
     * @return int
     */
    public function getKey78C4Ca4238A0B923820Dcc509A6F75849B()
    {
        return $this->key78c4ca4238a0b923820dcc509a6f75849b;
    }

    /**
     * Generated from protobuf field <code>int32 key78c4ca4238a0b923820dcc509a6f75849b = 78;</code>
     * @param int $var
     * @return $this
     */
    public function setKey78C4Ca4238A0B923820Dcc509A6F75849B($var)
    {
        GPBUtil::checkInt32($var);
        $this->key78c4ca4238a0b923820dcc509a6f75849b = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key8020231c8e224de4d79e923e29e23eb3a0 = 80;</code>
     * @return string
     */
    public function getKey8020231C8E224De4D79E923E29E23Eb3A0()
    {
        return $this->key8020231c8e224de4d79e923e29e23eb3a0;
    }

    /**
     * Generated from protobuf field <code>string key8020231c8e224de4d79e923e29e23eb3a0 = 80;</code>
     * @param string $var
     * @return $this
     */
    public function setKey8020231C8E224De4D79E923E29E23Eb3A0($var)
    {
        GPBUtil::checkString($var, True);
        $this->key8020231c8e224de4d79e923e29e23eb3a0 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key859d4568c009d203ab10e33ea9953a0264 = 85;</code>
     * @return string
     */
    public function getKey859D4568C009D203Ab10E33Ea9953A0264()
    {
        return $this->key859d4568c009d203ab10e33ea9953a0264;
    }

    /**
     * Generated from protobuf field <code>string key859d4568c009d203ab10e33ea9953a0264 = 85;</code>
     * @param string $var
     * @return $this
     */
    public function setKey859D4568C009D203Ab10E33Ea9953A0264($var)
    {
        GPBUtil::checkString($var, True);
        $this->key859d4568c009d203ab10e33ea9953a0264 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.key_3cfcd208495d565ef66e7dff9f98764da some_data = 86;</code>
     * @return \key_3cfcd208495d565ef66e7dff9f98764da
     */
    public function getSomeData()
    {
        return $this->some_data;
    }

    /**
     * Generated from protobuf field <code>.key_3cfcd208495d565ef66e7dff9f98764da some_data = 86;</code>
     * @param \key_3cfcd208495d565ef66e7dff9f98764da $var
     * @return $this
     */
    public function setSomeData($var)
    {
        GPBUtil::checkMessage($var, \key_3cfcd208495d565ef66e7dff9f98764da::class);
        $this->some_data = $var;

        return $this;
    }

}

