<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>key_1c5532ca6d72e0f2539d8faa9727d26b7</code>
 */
class key_1c5532ca6d72e0f2539d8faa9727d26b7 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.key_2a737a57334353dd24b748946ddbf6b06 ms_data = 1;</code>
     */
    protected $ms_data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \key_2a737a57334353dd24b748946ddbf6b06 $ms_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.key_2a737a57334353dd24b748946ddbf6b06 ms_data = 1;</code>
     * @return \key_2a737a57334353dd24b748946ddbf6b06
     */
    public function getMsData()
    {
        return $this->ms_data;
    }

    /**
     * Generated from protobuf field <code>.key_2a737a57334353dd24b748946ddbf6b06 ms_data = 1;</code>
     * @param \key_2a737a57334353dd24b748946ddbf6b06 $var
     * @return $this
     */
    public function setMsData($var)
    {
        GPBUtil::checkMessage($var, \key_2a737a57334353dd24b748946ddbf6b06::class);
        $this->ms_data = $var;

        return $this;
    }

}

