<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>key_1231d84139b3324b9a369643c152f8883f</code>
 */
class key_1231d84139b3324b9a369643c152f8883f extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 key1231d84139b3324b9a369643c152f8883f = 12;</code>
     */
    protected $key1231d84139b3324b9a369643c152f8883f = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $key1231d84139b3324b9a369643c152f8883f
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>fixed32 key1231d84139b3324b9a369643c152f8883f = 12;</code>
     * @return int
     */
    public function getKey1231D84139B3324B9A369643C152F8883F()
    {
        return $this->key1231d84139b3324b9a369643c152f8883f;
    }

    /**
     * Generated from protobuf field <code>fixed32 key1231d84139b3324b9a369643c152f8883f = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setKey1231D84139B3324B9A369643C152F8883F($var)
    {
        GPBUtil::checkUint32($var);
        $this->key1231d84139b3324b9a369643c152f8883f = $var;

        return $this;
    }

}

