<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>key_59a694d0d6a818c4af304617f622bf617</code>
 */
class key_59a694d0d6a818c4af304617f622bf617 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key150909e29648b4ed07afad0571b790be3 = 1;</code>
     */
    protected $key150909e29648b4ed07afad0571b790be3 = '';
    /**
     * Generated from protobuf field <code>string key355da256374eef17cbd2d2db703d0e202 = 3;</code>
     */
    protected $key355da256374eef17cbd2d2db703d0e202 = '';
    /**
     * Generated from protobuf field <code>string key59a694d0d6a818c4af304617f622bf617 = 5;</code>
     */
    protected $key59a694d0d6a818c4af304617f622bf617 = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key150909e29648b4ed07afad0571b790be3
     *     @type string $key355da256374eef17cbd2d2db703d0e202
     *     @type string $key59a694d0d6a818c4af304617f622bf617
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key150909e29648b4ed07afad0571b790be3 = 1;</code>
     * @return string
     */
    public function getKey150909E29648B4Ed07Afad0571B790Be3()
    {
        return $this->key150909e29648b4ed07afad0571b790be3;
    }

    /**
     * Generated from protobuf field <code>string key150909e29648b4ed07afad0571b790be3 = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey150909E29648B4Ed07Afad0571B790Be3($var)
    {
        GPBUtil::checkString($var, True);
        $this->key150909e29648b4ed07afad0571b790be3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key355da256374eef17cbd2d2db703d0e202 = 3;</code>
     * @return string
     */
    public function getKey355Da256374Eef17Cbd2D2Db703D0E202()
    {
        return $this->key355da256374eef17cbd2d2db703d0e202;
    }

    /**
     * Generated from protobuf field <code>string key355da256374eef17cbd2d2db703d0e202 = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey355Da256374Eef17Cbd2D2Db703D0E202($var)
    {
        GPBUtil::checkString($var, True);
        $this->key355da256374eef17cbd2d2db703d0e202 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key59a694d0d6a818c4af304617f622bf617 = 5;</code>
     * @return string
     */
    public function getKey59A694D0D6A818C4Af304617F622Bf617()
    {
        return $this->key59a694d0d6a818c4af304617f622bf617;
    }

    /**
     * Generated from protobuf field <code>string key59a694d0d6a818c4af304617f622bf617 = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setKey59A694D0D6A818C4Af304617F622Bf617($var)
    {
        GPBUtil::checkString($var, True);
        $this->key59a694d0d6a818c4af304617f622bf617 = $var;

        return $this;
    }

}

