<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>key_26d763f8ce1ca2f9b303e6b640ec33a7c</code>
 */
class key_26d763f8ce1ca2f9b303e6b640ec33a7c extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.key_917e66ef78164716386f5da926d39bdc7 unknown1 = 2;</code>
     */
    protected $unknown1 = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \key_917e66ef78164716386f5da926d39bdc7 $unknown1
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.key_917e66ef78164716386f5da926d39bdc7 unknown1 = 2;</code>
     * @return \key_917e66ef78164716386f5da926d39bdc7
     */
    public function getUnknown1()
    {
        return $this->unknown1;
    }

    /**
     * Generated from protobuf field <code>.key_917e66ef78164716386f5da926d39bdc7 unknown1 = 2;</code>
     * @param \key_917e66ef78164716386f5da926d39bdc7 $var
     * @return $this
     */
    public function setUnknown1($var)
    {
        GPBUtil::checkMessage($var, \key_917e66ef78164716386f5da926d39bdc7::class);
        $this->unknown1 = $var;

        return $this;
    }

}

