<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>key_2a737a57334353dd24b748946ddbf6b06</code>
 */
class key_2a737a57334353dd24b748946ddbf6b06 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key19f2871dddbc4c8335f587ffcb5c05758 = 1;</code>
     */
    protected $key19f2871dddbc4c8335f587ffcb5c05758 = '';
    /**
     * Generated from protobuf field <code>string key2a737a57334353dd24b748946ddbf6b06 = 2;</code>
     */
    protected $key2a737a57334353dd24b748946ddbf6b06 = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key19f2871dddbc4c8335f587ffcb5c05758
     *     @type string $key2a737a57334353dd24b748946ddbf6b06
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key19f2871dddbc4c8335f587ffcb5c05758 = 1;</code>
     * @return string
     */
    public function getKey19F2871Dddbc4C8335F587Ffcb5C05758()
    {
        return $this->key19f2871dddbc4c8335f587ffcb5c05758;
    }

    /**
     * Generated from protobuf field <code>string key19f2871dddbc4c8335f587ffcb5c05758 = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey19F2871Dddbc4C8335F587Ffcb5C05758($var)
    {
        GPBUtil::checkString($var, True);
        $this->key19f2871dddbc4c8335f587ffcb5c05758 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key2a737a57334353dd24b748946ddbf6b06 = 2;</code>
     * @return string
     */
    public function getKey2A737A57334353Dd24B748946Ddbf6B06()
    {
        return $this->key2a737a57334353dd24b748946ddbf6b06;
    }

    /**
     * Generated from protobuf field <code>string key2a737a57334353dd24b748946ddbf6b06 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey2A737A57334353Dd24B748946Ddbf6B06($var)
    {
        GPBUtil::checkString($var, True);
        $this->key2a737a57334353dd24b748946ddbf6b06 = $var;

        return $this;
    }

}

