<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>key_9ed41230f112ac3b7acb44db186ce7d03</code>
 */
class key_9ed41230f112ac3b7acb44db186ce7d03 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.key_863e33e1b7c536b8b6e462b15467a9fbf1 device_info = 1;</code>
     */
    protected $device_info = null;
    /**
     * Generated from protobuf field <code>.key_15cfcd208495d565ef66e7dff9f98764da unknown2 = 3;</code>
     */
    protected $unknown2 = null;
    /**
     * Generated from protobuf field <code>.key_26d763f8ce1ca2f9b303e6b640ec33a7c unknown3 = 6;</code>
     */
    protected $unknown3 = null;
    /**
     * Generated from protobuf field <code>.key_1c5532ca6d72e0f2539d8faa9727d26b7 ms_info = 9;</code>
     */
    protected $ms_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \key_863e33e1b7c536b8b6e462b15467a9fbf1 $device_info
     *     @type \key_15cfcd208495d565ef66e7dff9f98764da $unknown2
     *     @type \key_26d763f8ce1ca2f9b303e6b640ec33a7c $unknown3
     *     @type \key_1c5532ca6d72e0f2539d8faa9727d26b7 $ms_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.key_863e33e1b7c536b8b6e462b15467a9fbf1 device_info = 1;</code>
     * @return \key_863e33e1b7c536b8b6e462b15467a9fbf1
     */
    public function getDeviceInfo()
    {
        return $this->device_info;
    }

    /**
     * Generated from protobuf field <code>.key_863e33e1b7c536b8b6e462b15467a9fbf1 device_info = 1;</code>
     * @param \key_863e33e1b7c536b8b6e462b15467a9fbf1 $var
     * @return $this
     */
    public function setDeviceInfo($var)
    {
        GPBUtil::checkMessage($var, \key_863e33e1b7c536b8b6e462b15467a9fbf1::class);
        $this->device_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.key_15cfcd208495d565ef66e7dff9f98764da unknown2 = 3;</code>
     * @return \key_15cfcd208495d565ef66e7dff9f98764da
     */
    public function getUnknown2()
    {
        return $this->unknown2;
    }

    /**
     * Generated from protobuf field <code>.key_15cfcd208495d565ef66e7dff9f98764da unknown2 = 3;</code>
     * @param \key_15cfcd208495d565ef66e7dff9f98764da $var
     * @return $this
     */
    public function setUnknown2($var)
    {
        GPBUtil::checkMessage($var, \key_15cfcd208495d565ef66e7dff9f98764da::class);
        $this->unknown2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.key_26d763f8ce1ca2f9b303e6b640ec33a7c unknown3 = 6;</code>
     * @return \key_26d763f8ce1ca2f9b303e6b640ec33a7c
     */
    public function getUnknown3()
    {
        return $this->unknown3;
    }

    /**
     * Generated from protobuf field <code>.key_26d763f8ce1ca2f9b303e6b640ec33a7c unknown3 = 6;</code>
     * @param \key_26d763f8ce1ca2f9b303e6b640ec33a7c $var
     * @return $this
     */
    public function setUnknown3($var)
    {
        GPBUtil::checkMessage($var, \key_26d763f8ce1ca2f9b303e6b640ec33a7c::class);
        $this->unknown3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.key_1c5532ca6d72e0f2539d8faa9727d26b7 ms_info = 9;</code>
     * @return \key_1c5532ca6d72e0f2539d8faa9727d26b7
     */
    public function getMsInfo()
    {
        return $this->ms_info;
    }

    /**
     * Generated from protobuf field <code>.key_1c5532ca6d72e0f2539d8faa9727d26b7 ms_info = 9;</code>
     * @param \key_1c5532ca6d72e0f2539d8faa9727d26b7 $var
     * @return $this
     */
    public function setMsInfo($var)
    {
        GPBUtil::checkMessage($var, \key_1c5532ca6d72e0f2539d8faa9727d26b7::class);
        $this->ms_info = $var;

        return $this;
    }

}

