<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>key_29d4568c009d203ab10e33ea9953a0264</code>
 */
class key_29d4568c009d203ab10e33ea9953a0264 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 key1eccbc87e4b5ce2fe28308fd9f2a7baf3 = 1;</code>
     */
    protected $key1eccbc87e4b5ce2fe28308fd9f2a7baf3 = 0;
    /**
     * Generated from protobuf field <code>string key29d4568c009d203ab10e33ea9953a0264 = 2;</code>
     */
    protected $key29d4568c009d203ab10e33ea9953a0264 = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $key1eccbc87e4b5ce2fe28308fd9f2a7baf3
     *     @type string $key29d4568c009d203ab10e33ea9953a0264
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>fixed32 key1eccbc87e4b5ce2fe28308fd9f2a7baf3 = 1;</code>
     * @return int
     */
    public function getKey1Eccbc87E4B5Ce2Fe28308Fd9F2A7Baf3()
    {
        return $this->key1eccbc87e4b5ce2fe28308fd9f2a7baf3;
    }

    /**
     * Generated from protobuf field <code>fixed32 key1eccbc87e4b5ce2fe28308fd9f2a7baf3 = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setKey1Eccbc87E4B5Ce2Fe28308Fd9F2A7Baf3($var)
    {
        GPBUtil::checkUint32($var);
        $this->key1eccbc87e4b5ce2fe28308fd9f2a7baf3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key29d4568c009d203ab10e33ea9953a0264 = 2;</code>
     * @return string
     */
    public function getKey29D4568C009D203Ab10E33Ea9953A0264()
    {
        return $this->key29d4568c009d203ab10e33ea9953a0264;
    }

    /**
     * Generated from protobuf field <code>string key29d4568c009d203ab10e33ea9953a0264 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey29D4568C009D203Ab10E33Ea9953A0264($var)
    {
        GPBUtil::checkString($var, True);
        $this->key29d4568c009d203ab10e33ea9953a0264 = $var;

        return $this;
    }

}

