<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>key_120a3c98172949222cdbef9c4e44eb3bc</code>
 */
class key_120a3c98172949222cdbef9c4e44eb3bc extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.key_41cfcd208495d565ef66e7dff9f98764da options = 1;</code>
     */
    protected $options = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \key_41cfcd208495d565ef66e7dff9f98764da $options
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.key_41cfcd208495d565ef66e7dff9f98764da options = 1;</code>
     * @return \key_41cfcd208495d565ef66e7dff9f98764da
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>.key_41cfcd208495d565ef66e7dff9f98764da options = 1;</code>
     * @param \key_41cfcd208495d565ef66e7dff9f98764da $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \key_41cfcd208495d565ef66e7dff9f98764da::class);
        $this->options = $var;

        return $this;
    }

}

