<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>key_41cfcd208495d565ef66e7dff9f98764da</code>
 */
class key_41cfcd208495d565ef66e7dff9f98764da extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key3a2e900f2d9fc4ad8d718c519e1235f82 = 3;</code>
     */
    protected $key3a2e900f2d9fc4ad8d718c519e1235f82 = '';
    /**
     * Generated from protobuf field <code>fixed32 key4577bcc914f9e55d5e4e4f82f9f00e7d4 = 4;</code>
     */
    protected $key4577bcc914f9e55d5e4e4f82f9f00e7d4 = 0;
    /**
     * Generated from protobuf field <code>fixed32 key5d7a6170fcd40c9d43be7eb83295b0324 = 5;</code>
     */
    protected $key5d7a6170fcd40c9d43be7eb83295b0324 = 0;
    /**
     * Generated from protobuf field <code>fixed32 key6cfcd208495d565ef66e7dff9f98764da = 6;</code>
     */
    protected $key6cfcd208495d565ef66e7dff9f98764da = 0;
    /**
     * Generated from protobuf field <code>fixed32 key7eccbc87e4b5ce2fe28308fd9f2a7baf3 = 7;</code>
     */
    protected $key7eccbc87e4b5ce2fe28308fd9f2a7baf3 = 0;
    /**
     * Generated from protobuf field <code>fixed32 key8cfcd208495d565ef66e7dff9f98764da = 8;</code>
     */
    protected $key8cfcd208495d565ef66e7dff9f98764da = 0;
    /**
     * Generated from protobuf field <code>fixed32 key10cfcd208495d565ef66e7dff9f98764da = 10;</code>
     */
    protected $key10cfcd208495d565ef66e7dff9f98764da = 0;
    /**
     * Generated from protobuf field <code>fixed32 key11cfcd208495d565ef66e7dff9f98764da = 11;</code>
     */
    protected $key11cfcd208495d565ef66e7dff9f98764da = 0;
    /**
     * Generated from protobuf field <code>string key1247b90134230a35cfb0a68c8803199189 = 12;</code>
     */
    protected $key1247b90134230a35cfb0a68c8803199189 = '';
    /**
     * Generated from protobuf field <code>fixed32 key29cfcd208495d565ef66e7dff9f98764da = 29;</code>
     */
    protected $key29cfcd208495d565ef66e7dff9f98764da = 0;
    /**
     * Generated from protobuf field <code>fixed32 key37cfcd208495d565ef66e7dff9f98764da = 37;</code>
     */
    protected $key37cfcd208495d565ef66e7dff9f98764da = 0;
    /**
     * Generated from protobuf field <code>fixed32 key38cfcd208495d565ef66e7dff9f98764da = 38;</code>
     */
    protected $key38cfcd208495d565ef66e7dff9f98764da = 0;
    /**
     * Generated from protobuf field <code>fixed32 key41cfcd208495d565ef66e7dff9f98764da = 41;</code>
     */
    protected $key41cfcd208495d565ef66e7dff9f98764da = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key3a2e900f2d9fc4ad8d718c519e1235f82
     *     @type int $key4577bcc914f9e55d5e4e4f82f9f00e7d4
     *     @type int $key5d7a6170fcd40c9d43be7eb83295b0324
     *     @type int $key6cfcd208495d565ef66e7dff9f98764da
     *     @type int $key7eccbc87e4b5ce2fe28308fd9f2a7baf3
     *     @type int $key8cfcd208495d565ef66e7dff9f98764da
     *     @type int $key10cfcd208495d565ef66e7dff9f98764da
     *     @type int $key11cfcd208495d565ef66e7dff9f98764da
     *     @type string $key1247b90134230a35cfb0a68c8803199189
     *     @type int $key29cfcd208495d565ef66e7dff9f98764da
     *     @type int $key37cfcd208495d565ef66e7dff9f98764da
     *     @type int $key38cfcd208495d565ef66e7dff9f98764da
     *     @type int $key41cfcd208495d565ef66e7dff9f98764da
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key3a2e900f2d9fc4ad8d718c519e1235f82 = 3;</code>
     * @return string
     */
    public function getKey3A2E900F2D9Fc4Ad8D718C519E1235F82()
    {
        return $this->key3a2e900f2d9fc4ad8d718c519e1235f82;
    }

    /**
     * Generated from protobuf field <code>string key3a2e900f2d9fc4ad8d718c519e1235f82 = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey3A2E900F2D9Fc4Ad8D718C519E1235F82($var)
    {
        GPBUtil::checkString($var, True);
        $this->key3a2e900f2d9fc4ad8d718c519e1235f82 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key4577bcc914f9e55d5e4e4f82f9f00e7d4 = 4;</code>
     * @return int
     */
    public function getKey4577Bcc914F9E55D5E4E4F82F9F00E7D4()
    {
        return $this->key4577bcc914f9e55d5e4e4f82f9f00e7d4;
    }

    /**
     * Generated from protobuf field <code>fixed32 key4577bcc914f9e55d5e4e4f82f9f00e7d4 = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setKey4577Bcc914F9E55D5E4E4F82F9F00E7D4($var)
    {
        GPBUtil::checkUint32($var);
        $this->key4577bcc914f9e55d5e4e4f82f9f00e7d4 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key5d7a6170fcd40c9d43be7eb83295b0324 = 5;</code>
     * @return int
     */
    public function getKey5D7A6170Fcd40C9D43Be7Eb83295B0324()
    {
        return $this->key5d7a6170fcd40c9d43be7eb83295b0324;
    }

    /**
     * Generated from protobuf field <code>fixed32 key5d7a6170fcd40c9d43be7eb83295b0324 = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setKey5D7A6170Fcd40C9D43Be7Eb83295B0324($var)
    {
        GPBUtil::checkUint32($var);
        $this->key5d7a6170fcd40c9d43be7eb83295b0324 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key6cfcd208495d565ef66e7dff9f98764da = 6;</code>
     * @return int
     */
    public function getKey6Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key6cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key6cfcd208495d565ef66e7dff9f98764da = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setKey6Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key6cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key7eccbc87e4b5ce2fe28308fd9f2a7baf3 = 7;</code>
     * @return int
     */
    public function getKey7Eccbc87E4B5Ce2Fe28308Fd9F2A7Baf3()
    {
        return $this->key7eccbc87e4b5ce2fe28308fd9f2a7baf3;
    }

    /**
     * Generated from protobuf field <code>fixed32 key7eccbc87e4b5ce2fe28308fd9f2a7baf3 = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setKey7Eccbc87E4B5Ce2Fe28308Fd9F2A7Baf3($var)
    {
        GPBUtil::checkUint32($var);
        $this->key7eccbc87e4b5ce2fe28308fd9f2a7baf3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key8cfcd208495d565ef66e7dff9f98764da = 8;</code>
     * @return int
     */
    public function getKey8Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key8cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key8cfcd208495d565ef66e7dff9f98764da = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setKey8Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key8cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key10cfcd208495d565ef66e7dff9f98764da = 10;</code>
     * @return int
     */
    public function getKey10Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key10cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key10cfcd208495d565ef66e7dff9f98764da = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setKey10Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key10cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key11cfcd208495d565ef66e7dff9f98764da = 11;</code>
     * @return int
     */
    public function getKey11Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key11cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key11cfcd208495d565ef66e7dff9f98764da = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setKey11Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key11cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key1247b90134230a35cfb0a68c8803199189 = 12;</code>
     * @return string
     */
    public function getKey1247B90134230A35Cfb0A68C8803199189()
    {
        return $this->key1247b90134230a35cfb0a68c8803199189;
    }

    /**
     * Generated from protobuf field <code>string key1247b90134230a35cfb0a68c8803199189 = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setKey1247B90134230A35Cfb0A68C8803199189($var)
    {
        GPBUtil::checkString($var, True);
        $this->key1247b90134230a35cfb0a68c8803199189 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key29cfcd208495d565ef66e7dff9f98764da = 29;</code>
     * @return int
     */
    public function getKey29Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key29cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key29cfcd208495d565ef66e7dff9f98764da = 29;</code>
     * @param int $var
     * @return $this
     */
    public function setKey29Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key29cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key37cfcd208495d565ef66e7dff9f98764da = 37;</code>
     * @return int
     */
    public function getKey37Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key37cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key37cfcd208495d565ef66e7dff9f98764da = 37;</code>
     * @param int $var
     * @return $this
     */
    public function setKey37Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key37cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key38cfcd208495d565ef66e7dff9f98764da = 38;</code>
     * @return int
     */
    public function getKey38Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key38cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key38cfcd208495d565ef66e7dff9f98764da = 38;</code>
     * @param int $var
     * @return $this
     */
    public function setKey38Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key38cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key41cfcd208495d565ef66e7dff9f98764da = 41;</code>
     * @return int
     */
    public function getKey41Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key41cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key41cfcd208495d565ef66e7dff9f98764da = 41;</code>
     * @param int $var
     * @return $this
     */
    public function setKey41Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key41cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

}

