<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>key_15cfcd208495d565ef66e7dff9f98764da</code>
 */
class key_15cfcd208495d565ef66e7dff9f98764da extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed32 key7cfcd208495d565ef66e7dff9f98764da = 7;</code>
     */
    protected $key7cfcd208495d565ef66e7dff9f98764da = 0;
    /**
     * Generated from protobuf field <code>fixed32 key15cfcd208495d565ef66e7dff9f98764da = 15;</code>
     */
    protected $key15cfcd208495d565ef66e7dff9f98764da = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $key7cfcd208495d565ef66e7dff9f98764da
     *     @type int $key15cfcd208495d565ef66e7dff9f98764da
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>fixed32 key7cfcd208495d565ef66e7dff9f98764da = 7;</code>
     * @return int
     */
    public function getKey7Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key7cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key7cfcd208495d565ef66e7dff9f98764da = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setKey7Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key7cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key15cfcd208495d565ef66e7dff9f98764da = 15;</code>
     * @return int
     */
    public function getKey15Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key15cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key15cfcd208495d565ef66e7dff9f98764da = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setKey15Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key15cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

}

