<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>player_request</code>
 */
class player_request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.key_9ed41230f112ac3b7acb44db186ce7d03 device_data = 1;</code>
     */
    protected $device_data = null;
    /**
     * Generated from protobuf field <code>string videoId = 2;</code>
     */
    protected $videoId = '';
    /**
     * Generated from protobuf field <code>fixed32 key3cfcd208495d565ef66e7dff9f98764da = 3;</code>
     */
    protected $key3cfcd208495d565ef66e7dff9f98764da = 0;
    /**
     * Generated from protobuf field <code>.key_120a3c98172949222cdbef9c4e44eb3bc app_options = 4;</code>
     */
    protected $app_options = null;
    /**
     * Generated from protobuf field <code>fixed32 key5cfcd208495d565ef66e7dff9f98764da = 5;</code>
     */
    protected $key5cfcd208495d565ef66e7dff9f98764da = 0;
    /**
     * Generated from protobuf field <code>fixed32 key8cfcd208495d565ef66e7dff9f98764da = 8;</code>
     */
    protected $key8cfcd208495d565ef66e7dff9f98764da = 0;
    /**
     * Generated from protobuf field <code>string req_id = 23;</code>
     */
    protected $req_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \key_9ed41230f112ac3b7acb44db186ce7d03 $device_data
     *     @type string $videoId
     *     @type int $key3cfcd208495d565ef66e7dff9f98764da
     *     @type \key_120a3c98172949222cdbef9c4e44eb3bc $app_options
     *     @type int $key5cfcd208495d565ef66e7dff9f98764da
     *     @type int $key8cfcd208495d565ef66e7dff9f98764da
     *     @type string $req_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.key_9ed41230f112ac3b7acb44db186ce7d03 device_data = 1;</code>
     * @return \key_9ed41230f112ac3b7acb44db186ce7d03
     */
    public function getDeviceData()
    {
        return $this->device_data;
    }

    /**
     * Generated from protobuf field <code>.key_9ed41230f112ac3b7acb44db186ce7d03 device_data = 1;</code>
     * @param \key_9ed41230f112ac3b7acb44db186ce7d03 $var
     * @return $this
     */
    public function setDeviceData($var)
    {
        GPBUtil::checkMessage($var, \key_9ed41230f112ac3b7acb44db186ce7d03::class);
        $this->device_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string videoId = 2;</code>
     * @return string
     */
    public function getVideoId()
    {
        return $this->videoId;
    }

    /**
     * Generated from protobuf field <code>string videoId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVideoId($var)
    {
        GPBUtil::checkString($var, True);
        $this->videoId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key3cfcd208495d565ef66e7dff9f98764da = 3;</code>
     * @return int
     */
    public function getKey3Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key3cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key3cfcd208495d565ef66e7dff9f98764da = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setKey3Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key3cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.key_120a3c98172949222cdbef9c4e44eb3bc app_options = 4;</code>
     * @return \key_120a3c98172949222cdbef9c4e44eb3bc
     */
    public function getAppOptions()
    {
        return $this->app_options;
    }

    /**
     * Generated from protobuf field <code>.key_120a3c98172949222cdbef9c4e44eb3bc app_options = 4;</code>
     * @param \key_120a3c98172949222cdbef9c4e44eb3bc $var
     * @return $this
     */
    public function setAppOptions($var)
    {
        GPBUtil::checkMessage($var, \key_120a3c98172949222cdbef9c4e44eb3bc::class);
        $this->app_options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key5cfcd208495d565ef66e7dff9f98764da = 5;</code>
     * @return int
     */
    public function getKey5Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key5cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key5cfcd208495d565ef66e7dff9f98764da = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setKey5Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key5cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 key8cfcd208495d565ef66e7dff9f98764da = 8;</code>
     * @return int
     */
    public function getKey8Cfcd208495D565Ef66E7Dff9F98764Da()
    {
        return $this->key8cfcd208495d565ef66e7dff9f98764da;
    }

    /**
     * Generated from protobuf field <code>fixed32 key8cfcd208495d565ef66e7dff9f98764da = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setKey8Cfcd208495D565Ef66E7Dff9F98764Da($var)
    {
        GPBUtil::checkUint32($var);
        $this->key8cfcd208495d565ef66e7dff9f98764da = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string req_id = 23;</code>
     * @return string
     */
    public function getReqId()
    {
        return $this->req_id;
    }

    /**
     * Generated from protobuf field <code>string req_id = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setReqId($var)
    {
        GPBUtil::checkString($var, True);
        $this->req_id = $var;

        return $this;
    }

}

