<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>audio</code>
 */
class audio extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string audio_url = 2;</code>
     */
    protected $audio_url = '';
    /**
     * Generated from protobuf field <code>string format = 5;</code>
     */
    protected $format = '';
    /**
     * Generated from protobuf field <code>string size_format = 26;</code>
     */
    protected $size_format = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $audio_url
     *     @type string $format
     *     @type string $size_format
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string audio_url = 2;</code>
     * @return string
     */
    public function getAudioUrl()
    {
        return $this->audio_url;
    }

    /**
     * Generated from protobuf field <code>string audio_url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAudioUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->audio_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string format = 5;</code>
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * Generated from protobuf field <code>string format = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->format = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string size_format = 26;</code>
     * @return string
     */
    public function getSizeFormat()
    {
        return $this->size_format;
    }

    /**
     * Generated from protobuf field <code>string size_format = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setSizeFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->size_format = $var;

        return $this;
    }

}

