<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>player_videos</code>
 */
class player_videos extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>repeated .video videos = 2;</code>
     */
    private $videos;
    /**
     * Generated from protobuf field <code>repeated .audio audios = 3;</code>
     */
    private $audios;
    /**
     * Generated from protobuf field <code>string playback_url = 11;</code>
     */
    protected $playback_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type \video[]|\Google\Protobuf\Internal\RepeatedField $videos
     *     @type \audio[]|\Google\Protobuf\Internal\RepeatedField $audios
     *     @type string $playback_url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .video videos = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVideos()
    {
        return $this->videos;
    }

    /**
     * Generated from protobuf field <code>repeated .video videos = 2;</code>
     * @param \video[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVideos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \video::class);
        $this->videos = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .audio audios = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAudios()
    {
        return $this->audios;
    }

    /**
     * Generated from protobuf field <code>repeated .audio audios = 3;</code>
     * @param \audio[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAudios($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \audio::class);
        $this->audios = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string playback_url = 11;</code>
     * @return string
     */
    public function getPlaybackUrl()
    {
        return $this->playback_url;
    }

    /**
     * Generated from protobuf field <code>string playback_url = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaybackUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->playback_url = $var;

        return $this;
    }

}

