<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>player_response</code>
 */
class player_response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.requestData requestData = 1;</code>
     */
    protected $requestData = null;
    /**
     * Generated from protobuf field <code>.player_videos player_videos = 4;</code>
     */
    protected $player_videos = null;
    /**
     * Generated from protobuf field <code>.video_info video_info = 11;</code>
     */
    protected $video_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \requestData $requestData
     *     @type \player_videos $player_videos
     *     @type \video_info $video_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.requestData requestData = 1;</code>
     * @return \requestData
     */
    public function getRequestData()
    {
        return $this->requestData;
    }

    /**
     * Generated from protobuf field <code>.requestData requestData = 1;</code>
     * @param \requestData $var
     * @return $this
     */
    public function setRequestData($var)
    {
        GPBUtil::checkMessage($var, \requestData::class);
        $this->requestData = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.player_videos player_videos = 4;</code>
     * @return \player_videos
     */
    public function getPlayerVideos()
    {
        return $this->player_videos;
    }

    /**
     * Generated from protobuf field <code>.player_videos player_videos = 4;</code>
     * @param \player_videos $var
     * @return $this
     */
    public function setPlayerVideos($var)
    {
        GPBUtil::checkMessage($var, \player_videos::class);
        $this->player_videos = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.video_info video_info = 11;</code>
     * @return \video_info
     */
    public function getVideoInfo()
    {
        return $this->video_info;
    }

    /**
     * Generated from protobuf field <code>.video_info video_info = 11;</code>
     * @param \video_info $var
     * @return $this
     */
    public function setVideoInfo($var)
    {
        GPBUtil::checkMessage($var, \video_info::class);
        $this->video_info = $var;

        return $this;
    }

}

